sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0

## https://docs.travis-ci.com/user/languages/ruby#bundler-20
before_install:
  - gem update --system
  - gem install bundler

## https://docs.travis-ci.com/user/languages/ruby/#Dependency-Management
# install:

## https://docs.travis-ci.com/user/languages/ruby/#Default-Build-Script
script:
 - bundle exec rake spec

matrix:
  allow_failures:
    - rvm: 2.4.5
    - rvm: 2.5.3
    - rvm: 2.6.0
